spring:
  redis:
    database: 0
    cluster:
      max-redirects: 3
      nodes:
        - 10.4.65.55:7001
        - 10.4.65.55:7002
        - 10.4.65.55:7003
        - 10.4.65.55:7004
        - 10.4.65.55:7005
        - 10.4.65.55:7006
    lettuce:
      pool:
        max-idle: 100
        min-idle: 10
        max-active: 300
        max-wait: -1
    timeout: 30000
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: order
      auto-offset-reset: earliest
      bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  jackson:
    time-zone: GMT+8


